from typing import Protocol
from packages.core.entities.baseline import Baseline
from packages.core.entities.count_result import CountResult

class BaselineRepoPort(Protocol):
    def get(self, app_id: str, method: str) -> Baseline | None: ...
    def upsert(self, baseline: Baseline) -> None: ...
    def apply_from_result(self, baseline: Baseline | None, result: CountResult) -> Baseline: ...
